### ISSUE TITLE
Just wondering, is this dead?

### ISSUE THREAD

**Issue by IdrisQe** [lilypuree/BlockMagic#4]
Loved this mod, took a long break from Minecraft but now that I'm back I see that the Curseforge page is gone and the Github hasn't been touched in a year- I see it says it needs refactoring but is it just dead instead? I'm especially confused by the Curseforge being gone given that it worked fine most of the time in the versions it was available for (that I can recall anyway) so removing access to that made me feel the need to ask.

**Comment by lilypuree** [comment]
Yes I removed it from curseforge because I dropped the project.

**Comment by IdrisQe** [comment]
Ah, that's a shame, there's been no other mod that even attempts to do what this did, to this level anyway.
Understandable though, thanks for the response.
